packages:
  - packages/**
  - docs

catalog:
  "@solid-primitives/refs": ^1.1.2
  "@solid-primitives/resize-observer": ^2.1.3
  "@solid-primitives/scheduled": ^1.5.2
  rolldown-plugin-solid: ^0.2.1
  solid-js: ^1.9.10
  solid-tiny-context: 0.2.3
  solid-tiny-utils: 0.11.0
  tsdown: ^0.18.3
  typescript: ^5.9.3
  unocss: 66.5.10
  vitest: ^4.0.16


onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - esbuild
